In [2]:
import numpy as np

In [19]:
a = np.array([1,2,3],dtype='int32')
print (a)

[1 2 3]


In [6]:
b=np.array([[[1,2,3],[4,5,6.0],[7,8,9]]])
print(b)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]


In [7]:
# get dimension
a.ndim

1

In [8]:
b.ndim

3

In [10]:
#get shape
b.shape

(1, 3, 3)

In [15]:
#get type
a.dtype

dtype('int16')

In [20]:
#get size
a.itemsize

4

In [23]:
#get total size
a.nbytes

12