In [1]:
# Accessing/Changing specific elements, rows, columns etc

In [3]:
import numpy as np

In [4]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
#Get shape
a.shape

(2, 7)

In [9]:
#get a specific element [r, c]
a[1,5]

13

In [12]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
#get a specific column
a[:, 2]

array([ 3, 10])

In [15]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [19]:
a[1,5] = 20
print(a)
a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [20]:
#3d example

In [23]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
#Get specific element (work outside in)
b[0,1,1]

4

In [28]:
#replace
b[:,1,:] = [[9,9],[8,8]]

In [29]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [30]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
c[:,2]=20

In [32]:
print(c)

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]
