In [3]:
import numpy as np

In [5]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#matrix with data type
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [14]:
# Any other number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [28]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.27330957, 0.09878923, 0.83082006],
        [0.64215904, 0.55694833, 0.43488228]],

       [[0.30591831, 0.94860512, 0.05135422],
        [0.46554245, 0.39898954, 0.84018285]],

       [[0.21967406, 0.29013036, 0.8469249 ],
        [0.49054849, 0.18542971, 0.13803638]],

       [[0.61626708, 0.60720893, 0.73045173],
        [0.99510403, 0.90848239, 0.3777414 ]]])

In [37]:
# Random Int numbers
np.random.randint(4,7,size=(3,3))

array([[6, 5, 5],
       [4, 4, 5],
       [4, 4, 5]])

In [38]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
#repeat an array 
arr = np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
############# Copying arrays!!!

In [63]:
a = np.array([1,2,3])
b=a.copy()
b

array([1, 2, 3])

In [64]:
print(b)

[1 2 3]


In [58]:
b[0]=100

In [59]:
print(b)

[100   2   3]


In [60]:
print(a)

[100   2   3]
